### YamlMime:YamlDocument
documentType: LandingData
title: Documentazione di Ansible in Azure
metadata:
  title: 'Documentazione di Ansible in Azure - Esercitazioni, esempi, informazioni di riferimento e risorse'
  description: 'Informazioni su come usare Ansible per automatizzare il provisioning cloud, la gestione della configurazione e le distribuzioni dell''applicazione.'
  ms.service: azure
  keywords: 'ansible, azure, devops, esercitazioni, esempi, informazioni di riferimento'
  author: tomarchermsft
  manager: jeconnoc
  ms.author: tarcher
  ms.topic: landing-page
  ms.date: 04/22/2019
abstract:
  description: 'Usare <a href="https://www.ansible.com">Ansible</a> per automatizzare il provisioning cloud, la gestione della configurazione e le distribuzioni dell''applicazione.'
sections:
  - title: Guide introduttive di 5 minuti
    items:
      - type: paragraph
        text: Installare Ansible e usarlo per creare e gestire macchine virtuali Linux in Azure.
      - type: list
        style: icon48
        items:
          - image:
              src: /azure/media/index/azure_dev-9.svg
            text: Installare Ansible
            href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
          - image:
              src: /azure/media/index/VirtualMachine.svg
            text: Configurare una VM Linux
            href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
          - image:
              src: /azure/media/index/VirtualMachine.svg
            text: Gestire una VM Linux
            href: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
  - title: Esercitazioni dettagliate
    items:
      - type: paragraph
        text: 'Informazioni su come usare Ansible per creare e gestire l''infrastruttura di calcolo, di rete e di archiviazione di Azure.'
      - type: list
        style: unordered
        items:
          - html: '<a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Creare una macchina virtuale Linux, inclusi una rete virtuale, un indirizzo IP pubblico e una scheda di interfaccia di rete virtuale.</a>'
          - html: <a href="./ansible-run-playbook-in-cloudshell">Eseguire Ansible con Bash in Azure Cloud Shell.</a>
          - html: <a href="./ansible-manage-azure-dynamic-inventories">Creare e gestire un inventario dinamico delle risorse di Azure.</a>
          - html: <a href="./ansible-create-configure-vmss">Creare e gestire i set di scalabilità di macchine virtuali in Azure.</a>
          - html: <a href="./ansible-deploy-app-vmss">Distribuire applicazioni nei set di scalabilità di macchine virtuali in Azure.</a>
          - html: <a href="./ansible-create-configure-aks">Creare e gestire i cluster del servizio Azure Kubernetes.</a>
          - html: <a href="./ansible-create-configure-application-gateway">Gestire il traffico Web con un gateway applicazione di Azure.</a>
          - html: <a href="./ansible-auto-scale-vmss">Ridimensionare automaticamente i set di scalabilità di macchine virtuali in Azure con Ansible.</a>
          - html: <a href="./ansible-scale-azure-web-apps">Ridimensionare le app Web del servizio app di Azure con Ansible.</a>
          - html: '<a href="./ansible-create-configure-route-table">Creare, modificare o eliminare una tabella di route di Azure tramite Ansible.</a>'
  - title: riferimento
    items:
      - type: list
        style: cards
        className: cardsD
        items:
          - title: Ruoli dei playbook
            html: '<p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>'
          - title: Versioni e funzionalità
            html: <p><a href="./ansible-matrix.md">Matrice di funzionalità per moduli e ruoli</a></p>
          - title: Strumenti
            html: '<p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Estensione Visual Studio Code per Ansible</a></p>'